### ISSUE TITLE
Better test data : Relevant default test data to easily test and demonstrate

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim_backend#64]
Using "tracimcli db init --test-data"  create a prefilled tracim database with many workspace and files. Actually this environment is the same as used in some tests.

It should be usable for manually testing tracim quickly and probably also as a nice demonstration.
That why we probably need there relevant data (more diverse type of content, real "fake" content, etc...)

**Comment by lebouquetin** [comment]
note: `tracimcli db init --test-data` should be replaced by `tracimcli db init --with-test-data`. By the way, a better feature would be to allow to import data (so that we can choose which data to import without to modify the source code).

What is the structure of the current test data ? @inkhey could you point me to the source file in charge of generating these data ?

**Comment by inkhey** [comment]
@lebouquetin Actually test data are generate by fixture, so it's just source code to internal libs. 
For test_data, we rely on tracim/fixture/content.py Content Object with rely itself on tracim/fixture/users_and_groups Test and Base fixtures.

**Comment by inkhey** [comment]
https://github.com/tracim/tracim_backend/commit/03342866aa71ed7f69004f5078782cc519050d6b fix part of this (and some other commits to have working fixture for tests for all contents/case)

We probably need a distinct default data from test one, but now test one is more relevant.

**Comment by inkhey** [comment]
issue moved to https://github.com/tracim/tracim/issues/712
