### ISSUE TITLE
Endpoint GET /api/v2/workspaces/:workspace_id/contents should accepts filters as query param

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim_backend#97]
Endpoint GET /api/v2/workspaces/:workspace_id/contents
- Add a **query** param `filter` (string) that expects one of the content type slug (eg. html-documents, thread, file ...)
- Only returns contents that have type equals to `filter`

**Comment by inkhey** [comment]
Look like this bug is already corrected here : https://github.com/tracim/tracim_backend/pull/96 (see https://github.com/tracim/tracim_backend/pull/96/commits/2471e19b3c7ffbb4d43abe1c64111e1be8ff01da)
with "content_type" query param instead of filter (filter is not really clear, as you can always filter content of workspace by parent_id, show_archived, show_actived, show_deleted,...).

**Comment by lebouquetin** [comment]
@inkhey the filter about `content_type` is implemented ? Last time we talked about it, you told me that it was not implemented yet.

**Comment by inkhey** [comment]
@lebouquetin Last time it was not implemented. It is now available in #96 PR.
